version: "3.6"

services:
  cpp:
    image: cpp-build-env-ubuntu
    build:
      context: .
      dockerfile: Docker-chuser
      args:
        dockerimage: bojoe/cpp-build-env-ubuntu:latest
    network_mode: "host"
    privileged: true
    ipc: host
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    volumes:
      - /media:/media
      - /run:/run
      - /dev:/dev
      - ${WK_DIR}:/home/developer
      - $HOME:/home/$USER
      - $HOME/.Xauthority:/home/developer/.Xauthority
      - $HOME/.config/pulse/cookie:/home/developer/.config/pulse/cookie
      - /tmp:/tmp
    environment:
      - GROUP_ID
      - USER_ID
      - SSH_AUTH_SOCK
      - DISPLAY
      - DEVUSER=developer
      - DEVENV=ubuntu-build
      - HUNTER_ROOT=/home/$USER/.hunter
      - PROJECT_NAME
      - BUILD_DIR
      - XDG_RUNTIME_DIR
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
