#!/bin/bash

groupmod -g ${GROUP_ID} ${DEVUSER}
usermod -u ${USER_ID} -g ${GROUP_ID} ${DEVUSER}
export DISPLAY=$DISPLAY
export SSH_AUTH_SOCK=$SSH_AUTH_SOCK
export XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
export PULSE_SERVER=$PULSE_SERVER

su --whitelist-environment=\
SSH_AUTH_SOCK,\
XDG_RUNTIME_DIR, \
PULSE_SERVER, \
DISPLAY,\
DEVENV,\
HUNTER_ROOT,\
PROJECT_NAME,\
BUILD_DIR \
-l ${DEVUSER} $@
