version: "3.6"

services:
  cpp-creator-ide:
    build:
      context: .
      dockerfile: Docker-creator-file
      args:
        dockerimage: bojoe/cpp-build-env-ubuntu:latest
    container_name: dev-cpp-creator-ide
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/dri:/dev/dri
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
      - DISPLAY=$DISPLAY
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - $HOME:/home/developer
      - $HOME:/home/$USER
      - /tmp:/tmp

  cpp-qt-creator-ide:
    build:
      context: .
      dockerfile: Docker-creator-file
      args:
        dockerimage: bojoe/qt5-build-env-ubuntu:latest
    container_name: dev-qt-cpp-creator-ide
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/dri:/dev/dri
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
      - DISPLAY=$DISPLAY
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - $HOME:/home/developer
      - $HOME:/home/$USER
      - /tmp:/tmp

  genode-qt-creator-ide:
    build:
      context: .
      dockerfile: Docker-creator-file
      args:
        dockerimage: bojoe/genode-build-env-ubuntu:latest
    container_name: dev-genode-creator-ide
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/dri:/dev/dri
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
      - DISPLAY=$DISPLAY
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - $HOME:/home/developer
      - $HOME:/home/$USER
      - /tmp:/tmp

  wt-qt-creator-ide:
    build:
      context: .
      dockerfile: Docker-creator-file
      args:
        dockerimage: bojoe/wt-build-env-ubuntu:latest
    container_name: dev-wt-creator-ide
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/dri:/dev/dri
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
      - DISPLAY=$DISPLAY
    volumes:
      - $HOME:/home/developer
      - $HOME:/home/$USER
      - /tmp:/tmp

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
