version: "3.6"

services:
    cpp-ide:
      image: genode-cpp-ide
      build:
        args:
          dockerimage: bojoe/genode-build-env-ubuntu:latest
      volumes:
        - ${WK_DIR}/tools:/usr/local/genode
