version: '3.6'

services:
    build-poco-plain:
        image: bojoe/cpp-build-env-ubuntu:latest
        user: 0:0
        volumes:
            - ${WK_DIR}:/home/developer
            - $HOME:/home/$USER
            - /tmp:/tmp
        environment:
            - DEVENV=ubuntu-build
            - DEVUSER=developer
            - PROJECT_NAME=${PROJECT_NAME}
            - GROUP_ID=${GROUP_ID}
            - USER_ID=${USER_ID}
            - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
            - DISPLAY=${DISPLAY}
            - CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            - CMAKE_TOOLCHAIN_FILE=${CMAKE_CLANG_TOOLCHAIN_FILE}
            - CMAKE_MAKE_PROGRAM=ninja
            - HUNTER_ROOT=/home/$USER/.hunter
            - PROJECT_PATH=/home/developer/${PROJECT_PATH}
            - BUILD_DIR=${BUILD_DIR}
            - MYSQL_HOST="mysqldb"
            - POSTGRESQL_HOST="postgresdb"
            - REDIS_HOST="redisdb"
            - MONGODB_HOST="mongodb"
            - POCO_TEST_POSTGRES_CONN="DATABASE=postgres;SERVER=postgres;PORT=5432;"
        depends_on:
            - mysqldb
            - redisdb
            - postgresdb
            - mongodb
        networks:
            - mynet

    build-poco:
        image: bojoe/poco-build-env-ubuntu:latest
        user: 0:0
        volumes:
            - ${WK_DIR}:/home/developer
            - $HOME:/home/$USER
            - /tmp:/tmp
        environment:
            - DEVENV=ubuntu-build
            - DEVUSER=developer
            - PROJECT_NAME=${PROJECT_NAME}
            - GROUP_ID=${GROUP_ID}
            - USER_ID=${USER_ID}
            - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
            - DISPLAY=${DISPLAY}
            - CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            - CMAKE_TOOLCHAIN_FILE=${CMAKE_CLANG_TOOLCHAIN_FILE}
            - CMAKE_MAKE_PROGRAM=ninja
            - HUNTER_ROOT=/home/$USER/.hunter
            - PROJECT_PATH=/home/developer/${PROJECT_PATH}
            - BUILD_DIR=${BUILD_DIR}
            - MYSQL_HOST="mysqldb"
            - POSTGRESQL_HOST="postgresdb"
            - REDIS_HOST="redisdb"
            - MONGODB_HOST="mongodb"
            - POCO_TEST_POSTGRES_CONN="DATABASE=postgres;SERVER=postgres;PORT=5432;"
        depends_on:
            - mysqldb
            - redisdb
            - postgresdb
            - mongodb
        networks:
            - mynet

    build-poco-android:
        image: bojoe/cpp-android-ndk-build-env-ubuntu:latest
        user: 0:0
        volumes:
            - ${WK_DIR}:/home/developer
            - $HOME:/home/$USER
            - /tmp:/tmp
        environment:
            - DEVENV=android-build
            - DEVUSER=developer
            - PROJECT_NAME=${PROJECT_NAME}
            - GROUP_ID=${GROUP_ID}
            - USER_ID=${USER_ID}
            - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
            - DISPLAY=${DISPLAY}
            - CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            - CMAKE_TOOLCHAIN_FILE=${CMAKE_CLANG_TOOLCHAIN_FILE}
            - CMAKE_MAKE_PROGRAM=ninja
            - HUNTER_ROOT=/home/$USER/.hunter
            - PROJECT_PATH=/home/developer/${PROJECT_PATH}
            - BUILD_DIR=${BUILD_DIR}
            - MYSQL_HOST="mysqldb"
            - POSTGRESQL_HOST="postgresdb"
            - REDIS_HOST="redisdb"
            - MONGODB_HOST="mongodb"
            - POCO_TEST_POSTGRES_CONN="DATABASE=postgres;SERVER=postgres;PORT=5432;"
        depends_on:
            - mysqldb
            - redisdb
            - postgresdb
            - mongodb
        networks:
            - mynet

    ide-poco:
        build:
            context: .
            dockerfile: Docker-creator-file
            args:
                dockerimage: bojoe/poco-build-env-ubuntu:latest
        privileged: true
        security_opt:
            - seccomp=unconfined
        cap_add:
            - SYS_PTRACE
        devices:
            - /dev/dri:/dev/dri
        user: 0:0
        volumes:
            - /dev/bus/usb:/dev/bus/usb
            - ${WK_DIR}:/home/developer
            - $HOME:/home/$USER
            - $HOME/.Xauthority:/home/developer/.Xauthority
            - /tmp:/tmp
        environment:
            - DEVENV=ubuntu-build
            - DEVUSER=developer
            - PROJECT_NAME=${PROJECT_NAME}
            - GROUP_ID=${GROUP_ID}
            - USER_ID=${USER_ID}
            - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
            - DISPLAY=${DISPLAY}
            - CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            - CMAKE_TOOLCHAIN_FILE=${CMAKE_CLANG_TOOLCHAIN_FILE}
            - CMAKE_MAKE_PROGRAM=ninja
            - HUNTER_ROOT=/home/$USER/.hunter
            - PROJECT_PATH=/home/developer/${PROJECT_PATH}
            - BUILD_DIR=${BUILD_DIR}
            - MYSQL_HOST="mysqldb"
            - POSTGRESQL_HOST="postgresdb"
            - REDIS_HOST="redisdb"
            - MONGODB_HOST="mongodb"
            - POCO_TEST_POSTGRES_CONN="DATABASE=postgres;SERVER=postgres;PORT=5432;"
        network_mode: "host"
#        depends_on:
            #- mysqldb
            #- redisdb
            #- postgresdb
            #- mongodb
        #networks:
#            - mynet

    ide-poco-android:
        build:
            context: .
            dockerfile: Docker-creator-file
            args:
                dockerimage: bojoe/cpp-android-ndk-build-env-ubuntu:latest
        privileged: true
        security_opt:
            - seccomp=unconfined
        cap_add:
            - SYS_PTRACE
        devices:
            - /dev/dri:/dev/dri
        user: 0:0
        volumes:
            - /dev/bus/usb:/dev/bus/usb
            - ${WK_DIR}:/home/developer
            - $HOME:/home/$USER
            - $HOME/.Xauthority:/home/developer/.Xauthority
            - /tmp:/tmp
        environment:
            - DEVENV=android-build
            - DEVUSER=developer
            - PROJECT_NAME=${PROJECT_NAME}
            - GROUP_ID=${GROUP_ID}
            - USER_ID=${USER_ID}
            - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
            - DISPLAY=${DISPLAY}
            - CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            - CMAKE_TOOLCHAIN_FILE=${CMAKE_CLANG_TOOLCHAIN_FILE}
            - CMAKE_MAKE_PROGRAM=ninja
            - HUNTER_ROOT=/home/$USER/.hunter
            - PROJECT_PATH=/home/developer/${PROJECT_PATH}
            - BUILD_DIR=${BUILD_DIR}
            - MYSQL_HOST="mysqldb"
            - POSTGRESQL_HOST="postgresdb"
            - REDIS_HOST="redisdb"
            - MONGODB_HOST="mongodb"
            - POCO_TEST_POSTGRES_CONN="DATABASE=postgres;SERVER=postgres;PORT=5432;"
        network_mode: "host"
#        depends_on:
            #- mysqldb
            #- redisdb
            #- postgresdb
            #- mongodb
        #networks:
#            - mynet

    mysqldb:
        image: mysql:5.6
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: poco
            MYSQL_DATABASE: pocotestdb
        ports:
            - "3306:3306"
        networks:
            - mynet

    redisdb:
        image: redis:4
        ports:
            - "6379:6379"
        networks:
            - mynet

    mongodb:
        image: mongo:3.4
        ports:
            - "27017:27017"
        networks:
            - mynet
    
    postgresdb:
        image: postgres:9.4
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        networks:
            - mynet
networks:
    mynet:
        driver: bridge
